# EXERCISE 4 

### 1. create create a null vector / 1D array of size 10 and update fifth value to 11.

In [17]:
import numpy as np
one = np.zeros(10)
one[4]=11
one

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

### 2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [20]:
two = np.array([[9,6,4],
                [4,6,5]])
two
two.shape

(2, 3)

In [24]:
two1=two.reshape(3,2)
two1
two1.shape

(3, 2)

### 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [72]:
three = np.zeros(9)
a = three.reshape(3,3)
a[0,0:]=1
a[0:,0]=1
a[2,0:]=1
a[0:,2:]=1
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [71]:
C=np.ones(9).reshape(3,3)
C[1,1]=0
C

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

##### 4. Take a look at the following matrix. Access the [2, 1,1]

In [73]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [93]:
pilih = z[2,0,0:]
pilih
np.sort(pilih)[::-1]

array([2, 1, 1])

# ASSIGNMENT

### 1. Create a 4x4 matrix with values ranging from 0 to 3


In [97]:
from numpy import random
ass1 = random.randint(0,4, size=(4,4))
ass1

array([[2, 3, 1, 1],
       [3, 1, 0, 1],
       [0, 0, 0, 0],
       [2, 0, 1, 0]])

#### 2. Turn it into two arrays along the second axis

In [99]:
ass2 = np.hsplit(ass1,2)
ass2

[array([[2, 3],
        [3, 1],
        [0, 0],
        [2, 0]]),
 array([[1, 1],
        [0, 1],
        [0, 0],
        [1, 0]])]